version: '3'

services:

  analyzer-dummy:
    container_name: analyzer-dummy
    image: greenstamp/analyzer-dummy
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 4001:3000
    environment:
      DELIVER_RESULTS_ENDPOINT: 'http://51.210.255.156:3000/api/result'
